services:
  api:
    build: 
      context: .         # Context à la racine du projet
      dockerfile: Dockerfile  # Dockerfile dans docker/
    container_name: calculator-api-dev
    volumes:
      - ./app/:/app/
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=debug
      - PORT=8080